import "@/styles/globals.css";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ThemeSwap from "./components/ThemeSwap";
import Providers from "@/providers/providers";
import { notFound } from "next/navigation";
import { ClerkProvider } from "@clerk/nextjs";

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "fr" }];
}

export const metadata: Metadata = {
  title: "Track talk",
  description: "Generated by create next app",
};

const RootLayout = async ({ children, params: { locale } }) => {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang={locale} suppressHydrationWarning={true}>
        <body>
          <Providers locale={locale} messages={messages}>
            <Navbar>
              <ThemeSwap></ThemeSwap>
            </Navbar>
            <main className='container'>{children}</main>
            <Footer></Footer>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
